---
title: "Pseudotime"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r library}
# !/raid1/cqy/CD45-/Graduation_project
library(tidyverse)
library(ComplexHeatmap)
library(RColorBrewer)
```

```{r input}
fibro <- readr::read_csv("3.Stroma/fibro_expr_matrix.csv")
fibro_dpt <- readr::read_csv("3.Stroma/fibro_diff_dpt.csv")
fibro <- fibro %>% column_to_rownames("...1")
fibro_dpt <- fibro_dpt %>% column_to_rownames("...1")
fibro_dpt <- fibro_dpt %>% 
  arrange(dpt_pseudotime) %>%
  mutate(adjusted_dpt = case_when(
    diff_cluster == "0" ~ dpt_pseudotime,
    diff_cluster == "1" ~ ifelse(row_number() %% 2 == 0, -dpt_pseudotime, dpt_pseudotime),
    diff_cluster == "2" ~ -dpt_pseudotime)) %>%
  arrange(adjusted_dpt)
fibro <- fibro[rownames(fibro_dpt), ]
```
```{r loess regression}
library(gam)
t <- fibro_dpt$adjusted_dpt
result <- apply(fibro, 2, function(z){
  d <- data.frame(z = z, t = t)
  tmp <- gam(z ~ lo(t), data = d)
  p <- summary(tmp)[4][[1]][1,5]
  c(p, predict(tmp))
})
gam_pval <- result[1,]
pred <- result[2:(nrow(fibro) + 1),]
pred <- as.data.frame(pred)
```

```{r gene selection}
gam_pval_adj <- p.adjust(gam_pval, method = "BH")
sgenes <- names(gam_pval_adj[gam_pval_adj < 0.01])
pred_filtered <- pred[, sgenes]
write.csv(as.data.frame(gam_pval), "3.Stroma/gam_pval.csv", row.names = TRUE)
write.csv(as.data.frame(gam_pval_adj), "3.Stroma/gam_pval_adj.csv", row.names = TRUE)
```

```{r clustering}
library(cluster)
pred_filtered <- as.data.frame(scale(pred_filtered))
dist_matrix <- cor(pred_filtered, method = "pearson")
dist_matrix <- RFLPtools::sim2dist(dist_matrix, maxSim = 1)
hc <- hclust(dist_matrix, method = "ward.D2")
ct <- cutree(hc, 6)
ct <- ct %>% as.data.frame() %>% rownames_to_column("genes")
colnames(ct) <- c("genes", "cluster")
rownames(ct) <- ct$genes
gene_list <- sgenes[hc$order]
```

```{r heatmap}
# Sampling
pred_sample <- sample_n(pred_filtered, 2000)

# Dpt
pred_dpt_sample <- fibro_dpt[rownames(pred_sample), ]
pred_dpt_sample <- pred_dpt_sample %>% 
  arrange(adjusted_dpt) %>%
  select(diff_cluster, dpt_pseudotime)
pred_dpt_sample$diff_cluster <- factor(pred_dpt_sample$diff_cluster)
pred_dpt_sample$dpt_pseudotime <- ifelse(pred_dpt_sample$dpt_pseudotime > 0.6,
                                         0.6,
                                         pred_dpt_sample$dpt_pseudotime)

# Gene list
ct <- ct[gene_list, ]
ct$cluster <- factor(ct$cluster, levels = c(1,5,2,3,6,4))
ct <- ct %>% arrange(cluster, decreasing = FALSE)
gene_list <- ct$genes
ct <- ct %>% select(cluster)
write.csv(ct, "3.Stroma/pseudotime_gene_cluster.csv", row.names = TRUE)
pred_sample <- pred_sample[rownames(pred_dpt_sample), gene_list]

# Annotation colors
diff_cluster_cols <- c("#7fcba4", "#4b65af", "#f46f44") 
names(diff_cluster_cols) <- c(0,1,2)
time_cols <- colorRampPalette(rev(brewer.pal(n = 11, name = "RdBu")))(100)
cluster_cols <- c("#264653", "#2a9d8e", "#e9c46b", "#f3a261", "#e66f51", "#bf1e2e")
names(cluster_cols) <- c(1,5,2,3,6,4)

ann_colors <- list(diff_cluster = diff_cluster_cols, 
                   dpt_pseudotime = time_cols,
                   cluster = cluster_cols)

pheatmap(t(pred_sample),
         color = colorRampPalette(rev(brewer.pal(n = 11, name = "Spectral")))(100),
         breaks = seq(-2, 2, length.out = 100),
         cluster_rows = FALSE, cluster_cols= FALSE,
         treeheight_row = 0, treeheight_col = 0,
         show_rownames = FALSE, show_colnames = FALSE, fontsize_row = 2,
         annotation_row = ct, annotation_col = pred_dpt_sample,
         annotation_colors = ann_colors)
```

```{r}
ct <- ct %>% rownames_to_column("gene")
ct$pval <- gam_pval_adj[ct$gene]
ct <- ct %>% arrange(pval)
```

```{r aucell curve plot}
aucell <- read_csv("3.Stroma/pseudotime_aucell.csv")
aucell <- aucell %>% column_to_rownames("...1")
aucell$dpt_pseudotime <- fibro_dpt[rownames(aucell), "dpt_pseudotime"]
aucell$diff_cluster <- fibro_dpt[rownames(aucell), "diff_cluster"]

cluster_cols <- c("#264653", "#2a9d8e", "#e9c46b", "#f3a261", "#e66f51", "#bf1e2e")
names(cluster_cols) <- c(1,5,2,3,6,4)

# 1 -> 0
toplot <- aucell %>% filter(diff_cluster %in% c(0,1)) %>%
  filter(dpt_pseudotime < 0.6)
toplot <- toplot %>% select(1:6, dpt_pseudotime) %>%
  pivot_longer(1:6, names_to = "cluster", values_to = "pred")
toplot$cluster <- factor(toplot$cluster, levels = c(1,5,2,3,6,4))

ggplot(toplot, aes(x = dpt_pseudotime, y = pred, color = cluster)) + 
  geom_smooth(method = "loess", se = FALSE) +
  facet_wrap("cluster", ncol = 1) +
  scale_color_manual(values = cluster_cols) +
  theme_bw()

# 1 -> 2
toplot <- aucell %>% filter(diff_cluster %in% c(1,2)) %>%
  filter(dpt_pseudotime < 0.6)
toplot <- toplot %>% select(1:6, dpt_pseudotime) %>%
  pivot_longer(1:6, names_to = "cluster", values_to = "pred")
toplot$cluster <- factor(toplot$cluster, levels = c(1,5,2,3,6,4))

ggplot(toplot, aes(x = dpt_pseudotime, y = pred, color = cluster)) + 
  geom_smooth(method = "loess", se = FALSE) +
  facet_wrap("cluster", ncol = 1) +
  scale_color_manual(values = cluster_cols) +
  theme_bw()
```

```{r GO analysis}
library(org.Hs.eg.db)
library(clusterProfiler)

gene_sig <- filter(ct, cluster == 1)
gene_sig <- bitr(gene_sig$gene,
                 fromType = 'SYMBOL',
                 toType = 'ENTREZID',
                 OrgDb = 'org.Hs.eg.db')
ego_BP <- enrichGO(gene = gene_sig[,2],
                   OrgDb = org.Hs.eg.db,
                   keyType = "ENTREZID",
                   ont = "BP",
                   pAdjustMethod = "BH",
                   pvalueCutoff = 0.01,
                   qvalueCutoff = 0.01,
                   readable = TRUE)
ego_BP <- ego_BP@result %>% 
  arrange(qvalue, decreasing = FALSE) %>%
  select(Description, qvalue)
ego_BP$cluster <- 1
toplot <- ego_BP[c(1,4),]

gene_sig <- filter(ct, cluster == 5)
gene_sig <- bitr(gene_sig$gene,
                 fromType = 'SYMBOL',
                 toType = 'ENTREZID',
                 OrgDb = 'org.Hs.eg.db')
ego_BP <- enrichGO(gene = gene_sig[,2],
                   OrgDb = org.Hs.eg.db,
                   keyType = "ENTREZID",
                   ont = "BP",
                   pAdjustMethod = "BH",
                   pvalueCutoff = 0.01,
                   qvalueCutoff = 0.01,
                   readable = TRUE)
ego_BP <- ego_BP@result %>% 
  arrange(qvalue, decreasing = FALSE) %>%
  select(Description, qvalue)
ego_BP$cluster <- 5
toplot <- rbind(toplot, ego_BP[c(1,6),])

gene_sig <- filter(ct, cluster == 2)
gene_sig <- bitr(gene_sig$gene,
                  fromType = 'SYMBOL',
                  toType = 'ENTREZID',
                  OrgDb = 'org.Hs.eg.db')
ego_BP <- enrichGO(gene = gene_sig[,2],
                  OrgDb = org.Hs.eg.db,
                  keyType = "ENTREZID",
                  ont = "BP",
                  pAdjustMethod = "BH",
                  pvalueCutoff = 0.01,
                  qvalueCutoff = 0.01,
                  readable = TRUE)
ego_BP <- ego_BP@result %>% 
  arrange(qvalue, decreasing = FALSE) %>%
  select(Description, qvalue)
ego_BP$cluster <- 2
toplot <- rbind(toplot, ego_BP[c(12,13),])

gene_sig <- filter(ct, cluster == 3)
gene_sig <- bitr(gene_sig$gene,
                 fromType = 'SYMBOL',
                 toType = 'ENTREZID',
                 OrgDb = 'org.Hs.eg.db')
ego_BP <- enrichGO(gene = gene_sig[,2],
                   OrgDb = org.Hs.eg.db,
                   keyType = "ENTREZID",
                   ont = "BP",
                   pAdjustMethod = "BH",
                   pvalueCutoff = 0.01,
                   qvalueCutoff = 0.01,
                   readable = TRUE)
ego_BP <- ego_BP@result %>% 
  arrange(qvalue, decreasing = FALSE) %>%
  select(Description, qvalue)
ego_BP$cluster <- 3
toplot <- rbind(toplot, ego_BP[c(2,4),])

gene_sig <- filter(ct, cluster == 6)
gene_sig <- bitr(gene_sig$gene,
                 fromType = 'SYMBOL',
                 toType = 'ENTREZID',
                 OrgDb = 'org.Hs.eg.db')
ego_BP <- enrichGO(gene = gene_sig[,2],
                   OrgDb = org.Hs.eg.db,
                   keyType = "ENTREZID",
                   ont = "BP",
                   pAdjustMethod = "BH",
                   pvalueCutoff = 0.01,
                   qvalueCutoff = 0.01,
                   readable = TRUE)
ego_BP <- ego_BP@result %>% 
  arrange(qvalue, decreasing = FALSE) %>%
  select(Description, qvalue)
ego_BP$cluster <- 6
toplot <- rbind(toplot, ego_BP[c(1,4),])

gene_sig <- filter(ct, cluster == 4)
gene_sig <- bitr(gene_sig$gene,
                 fromType = 'SYMBOL',
                 toType = 'ENTREZID',
                 OrgDb = 'org.Hs.eg.db')
ego_BP <- enrichGO(gene = gene_sig[,2],
                   OrgDb = org.Hs.eg.db,
                   keyType = "ENTREZID",
                   ont = "BP",
                   pAdjustMethod = "BH",
                   pvalueCutoff = 0.01,
                   qvalueCutoff = 0.01,
                   readable = TRUE)
ego_BP <- ego_BP@result %>% 
  arrange(qvalue, decreasing = FALSE) %>%
  select(Description, qvalue)
ego_BP$cluster <- 4
toplot <- rbind(toplot, ego_BP[c(1,4),])

toplot$cluster <- factor(toplot$cluster, levels = c(1,5,2,3,6,4))
toplot$Description <- factor(toplot$Description, levels = rev(toplot$Description))
cluster_cols <- c("#264653", "#2a9d8e", "#e9c46b", "#f3a261", "#e66f51", "#bf1e2e")
names(cluster_cols) <- c(1,5,2,3,6,4)
ggplot(toplot, aes(x = -log10(qvalue), y = Description, fill = cluster)) +
  geom_col() +
  scale_fill_manual(values = cluster_cols) +
  theme_classic() +
  theme(panel.grid.minor = element_blank(),
        panel.grid.major = element_blank())
```

